export const crimeCategoryMap: { [key: string]: string } = {
  'drugs': 'Drug Related',
  'other-theft': 'Theft',
  'bicycle-theft': 'Bicycle Theft',
  'criminal-damage-arson': 'Arson',
  'burglary': 'Burglary',
  'anti-social-behaviour': 'Anti-social Behaviour',
  'possession-of-weapons': 'Weapon Possession',
  'public-order': 'Public Order',
  'robbery': 'Robbery',
  'shoplifting': 'Shoplifting',
  'theft-from-the-person': 'Personal Theft/Mugging',
  'vehicle-crime': 'Vehicle Crime',
  'violent-crime': 'Violent Crime',
  'other-crime': 'Other',
  'total': 'Total'
};

export const crimeOutcomesMap: { [key: string]: string } = {
  'awaiting-court-result': 'Awaiting court outcome',
  'court-result-unavailable': 'Court result unavailable',
  'unable-to-proceed': 'Court case unable to proceed',
  'local-resolution': 'Local resolution',
  'no-further-action': 'Investigation complete; no suspect identified',
  'deprived-of-property': 'Offender deprived of property',
  'fined': 'Offender fined',
  'absolute-discharge': 'Offender given absolute discharge',
  'cautioned': 'Offender given a caution',
  'drugs-possession-warning': 'Offender given a drugs possession warning',
  'penalty-notice-issued': 'Offender given a penalty notice',
  'community-penalty': 'Offender given community sentence',
  'conditional-discharge': 'Offender given conditional discharge',
  'suspended-sentence': 'Offender given suspended prison sentence',
  'imprisoned': 'Offender sent to prison',
  'other-court-disposal': 'Offender otherwise dealt with',
  'compensation': 'Offender ordered to pay compensation',
  'sentenced-in-another-case': 'Suspect charged as part of another case',
  'charged': 'Suspect charged',
  'not-guilty': 'Defendant found not guilty',
  'sent-to-crown-court': 'Defendant sent to Crown Court',
  'unable-to-prosecute': 'Unable to prosecute suspect',
  'formal-action-not-in-public-interest': 'Formal action is not in the public interest',
  'action-taken-by-another-organisation': 'Action to be taken by another organisation',
  'further-investigation-not-in-public-interest': 'Further investigation is not in the public interest',
  'further-action-not-in-public-interest': 'Further action is not in the public interest',
  'under-investigation': 'Under investigation',
  'status-update-unavailable': 'Status update unavailable',
  'Under investigation': 'Under investigation'
};